# Cloudflare Pages configuration

[build]
  command = "pnpm build"
  publish = "dist"
  node_version = "18"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--version"

[site]
  bucket = "./dist"
  entry-point = "."